### ISSUE TITLE
please choose a valid license

### ISSUE THREAD

**Issue by onkelbeh** [jafar-atili/pyElectra#3]
Hi,

first, thanks for your work. I would like to include your library in my Home Assistant Gentoo overlay, https://github.com/onkelbeh/HomeAssistantRepository/, because it is actively used by an integration.

Same here, you have not selected a license, not here, and not on pypi, so I am also asking for clarification.
According to Gentoo's license guidelines, it is not allowed to redistribute a package without a license (https://devmanual.gentoo.org/general-concepts/licenses/index.html).

Today, I added your integration with an "all-rights-reserved" tag, but this forbids redistribution and usage of gentoo's mirror system.

At the bottom of my [README.md](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/README.md) you can find some (outdated) license stats, perhaps this helps your decision. Thanks a lot in advance.

\B.

**Comment by joostlek** [comment]
@jafar-atili From the Home Assistant project we also want to request you do adhere to this request, or the electrasmart integration could be considered to be dropped from the project.

**Comment by jafar-atili** [comment]
Apache License 2.0 was added to the project
https://github.com/jafar-atili/pyElectra/commit/06e94973e37064c09cb0faa374f461b4a1e30b12

**Comment by joostlek** [comment]
Could you also add `License :: OSI Approved :: Apache Software License` to the classifiers, and after that release and maybe bump in Home Assistant?

**Comment by joostlek** [comment]
Kind reminder to do a release and bump in Home Assistant :)
